# Generated by Django 4.1 on 2022-09-02 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_cluster', models.CharField(max_length=255)),
                ('nombre_cluster', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_unidad', models.CharField(max_length=255)),
                ('nombre_unidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Planeador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_planeador', models.CharField(max_length=255)),
                ('apellido_planeador', models.CharField(max_length=255)),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeadores.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_equipo', models.CharField(max_length=255)),
                ('om', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeadores.cluster')),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeadores.familia')),
                ('planeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeadores.planeador')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeadores.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeadores.unidad'),
        ),
    ]
