# Generated by Django 4.1 on 2022-09-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planeadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='sigla_unidad',
        ),
    ]
