# Generated by Django 4.1 on 2022-09-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeadores', '0002_remove_unidad_sigla_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='numero_unidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
