# Generated by Django 4.1 on 2022-09-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeadores', '0004_alter_unidad_numero_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacion',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeadores.unidad'),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='estado',
            field=models.CharField(default='En planeación', editable=False, max_length=255),
        ),
        migrations.CreateModel(
            name='PlaneacionSAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('om', models.IntegerField()),
                ('tag_equipo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.CharField(default='En planeación', editable=False, max_length=255)),
                ('familia', models.CharField(max_length=255)),
                ('cluster', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=255)),
                ('planeador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planeadores.planeador')),
            ],
        ),
    ]
