# Generated by Django 4.1 on 2022-09-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planeadores', '0005_planeacion_descripcion_alter_cluster_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeador',
            name='registro',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planeacionsap',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planeadores.familia'),
        ),
    ]
