# Generated by Django 4.1 on 2022-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planeadores', '0006_planeador_registro_alter_planeacionsap_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeador',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
